services:
  mysql:
    container_name: banco
    image: elersonalves/mysql-sparrow
    restart: always
    volumes:
        - mysql_data:/var/lib/mysql
    ports:
        - "3306:3306"
  node:
    container_name: node
    image: elersonalves/sparrow
    restart: always
    ports:
      - "3333:3333"
volumes:
  mysql_data: {}
